openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: Weather service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:3000
paths:
  /admin/country/create:
    post:
      tags:
        - Admin countires methods
      summary: cities
      description: Getting cities
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - code
              properties:
                code:
                  type: string
                  example: US
                isActive:
                  type: boolean
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception
          
  /admin/country/list:
    get:
      tags:
        - Admin countires methods
      summary: Getting cities
      description: Getting cities
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception
                    
  /admin/city/create:
    post:
      tags:
        - Admin cities methods
      summary: cities
      description: Getting cities
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: 
                - countryId
                - name
              properties:
                countryId:
                  type: integer
                  format: int64
                  example: 1
                latitude:
                  type: number
                  format: float
                  example: 51.50
                longitude:
                  type: number
                  format: float
                  example: -0.11
                name:
                  type: string
                  example: London
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception

  /admin/city/list:
    get:
      tags:
        - Admin cities methods
      summary: Getting cities
      description: Getting cities
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/City'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception
          
  /admin/weather/sync:
    post:
      tags:
        - Admin weather methods
      summary: cities
      description: Getting cities
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: 
                - cityId
              properties:
                cityId:
                    type: integer
                    example: 1
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception

components:
  schemas:
    City: 
      type: object
      required: 
        - id
        - countryId
        - name
        - latitude
        - longitude
        - createdAt
        - updatedAt
      properties:
        id:
          type: integer
          format: int64
          example: 10
        countryId:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: London
          
        latitude:
          type: number
          format: float
          example: 51.50
          
        longitude:
          type: number
          format: float
          example: -0.11
          
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
          
    Country: 
      type: object
      required: 
        - id
        - code
        - createdAt
        - updatedAt
      properties:
        id:
          type: integer
          format: int64
          example: 1
        code:
          type: string
          example: US
        isActive:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    
